print('Olá')
print("Vodka")
print('Olá','Vanderlei','Dieter','Gabriel','Felipe')
print('Olá','\nVanderlei','\nDieter','\nGabriel','\nFelipe')
print('Olá','\n\tVanderlei','\n\tDieter','\n\tGabriel','\n\tFelipe')
